import { supabase } from "@/integrations/supabase/client";
import { format } from "date-fns";

interface CreateLedgerEntryParams {
  entryType: "income" | "expense";
  category: string;
  description: string;
  amount: number;
  entryDate?: Date;
  memberId?: string;
  dailyPassUserId?: string;
  paymentId?: string;
  trainerId?: string;
  ptSubscriptionId?: string;
  notes?: string;
  isAutoGenerated?: boolean;
  branchId?: string;
}

export const createLedgerEntry = async (params: CreateLedgerEntryParams) => {
  const { error } = await supabase.from("ledger_entries").insert({
    entry_type: params.entryType,
    category: params.category,
    description: params.description,
    amount: params.amount,
    entry_date: params.entryDate ? format(params.entryDate, "yyyy-MM-dd") : format(new Date(), "yyyy-MM-dd"),
    member_id: params.memberId || null,
    daily_pass_user_id: params.dailyPassUserId || null,
    payment_id: params.paymentId || null,
    trainer_id: params.trainerId || null,
    pt_subscription_id: params.ptSubscriptionId || null,
    notes: params.notes || null,
    is_auto_generated: params.isAutoGenerated ?? true,
    branch_id: params.branchId || null,
  });

  if (error) {
    console.error("Error creating ledger entry:", error);
  }

  return { error };
};

// Helper to calculate trainer percentage expense
export const calculateTrainerPercentageExpense = async (
  trainerId: string,
  ptFeeAmount: number,
  memberId?: string,
  dailyPassUserId?: string,
  ptSubscriptionId?: string,
  memberName?: string,
  branchId?: string
) => {
  // First, get the trainer info
  const { data: trainer, error: trainerError } = await supabase
    .from("personal_trainers")
    .select("name, payment_category, percentage_fee")
    .eq("id", trainerId)
    .single();

  if (trainerError || !trainer) {
    console.error("Error fetching trainer:", trainerError);
    return;
  }

  // Only create expense if trainer is on monthly + percentage basis
  if (trainer.payment_category === "monthly_percentage" && trainer.percentage_fee > 0) {
    const percentageAmount = (ptFeeAmount * trainer.percentage_fee) / 100;
    
    if (percentageAmount > 0) {
      await createLedgerEntry({
        entryType: "expense",
        category: "trainer_percentage",
        description: `${trainer.name} - ${trainer.percentage_fee}% of PT fee${memberName ? ` for ${memberName}` : ""}`,
        amount: percentageAmount,
        memberId,
        dailyPassUserId,
        trainerId,
        ptSubscriptionId,
        isAutoGenerated: true,
        branchId,
      });
    }
  }
};

// Create income entry for gym membership/renewal/daily pass
export const createMembershipIncomeEntry = async (
  amount: number,
  category: "gym_membership" | "gym_renewal" | "daily_pass" | "pt_subscription" | "joining_fee",
  description: string,
  memberId?: string,
  dailyPassUserId?: string,
  paymentId?: string,
  branchId?: string
) => {
  await createLedgerEntry({
    entryType: "income",
    category,
    description,
    amount,
    memberId,
    dailyPassUserId,
    paymentId,
    isAutoGenerated: true,
    branchId,
  });
};

export const useLedger = () => {
  return {
    createLedgerEntry,
    calculateTrainerPercentageExpense,
    createMembershipIncomeEntry,
  };
};
